package envfile

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"
)

func Read(path string) (map[string]string, error) {
	values := map[string]string{}
	file, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return values, nil
		}
		return nil, err
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, found := strings.Cut(line, "=")
		if !found {
			return nil, fmt.Errorf("invalid env line: %q", line)
		}
		values[strings.TrimSpace(key)] = strings.Trim(strings.TrimSpace(value), `"'`)
	}
	return values, scanner.Err()
}

func Render(entries [][2]string) string {
	lines := []string{
		"# Generated by `codex-telegram-bridge setup`.",
		"# Review and keep this file private because it contains bot credentials.",
		"",
	}
	for _, entry := range entries {
		lines = append(lines, fmt.Sprintf("%s=%s", entry[0], entry[1]))
	}
	return strings.Join(lines, "\n") + "\n"
}

func MergeKnownEntries(existing map[string]string, known [][2]string) [][2]string {
	knownKeys := map[string]struct{}{}
	entries := make([][2]string, 0, len(known)+len(existing))
	for _, entry := range known {
		knownKeys[entry[0]] = struct{}{}
		entries = append(entries, entry)
	}

	var passthroughKeys []string
	for key := range existing {
		if _, ok := knownKeys[key]; !ok {
			passthroughKeys = append(passthroughKeys, key)
		}
	}
	sort.Strings(passthroughKeys)
	for _, key := range passthroughKeys {
		entries = append(entries, [2]string{key, existing[key]})
	}
	return entries
}
