import { homedir } from "node:os";
import { join, resolve } from "node:path";
import { serializeEnvironmentFile } from "../config/env-file.js";
import {
  hashVerificationPassword,
  normalizeVerificationPassword
} from "../security/verification-password.js";
import type { AppLogLevel } from "../config/index.js";
import type { SetupInputValues, SetupResolvedValues } from "./setup-shared.js";

export function renderEnvironmentFile(
  entries: readonly [string, string][]
): string {
  const header = [
    "# Generated by `codex-telegram-bridge setup`.",
    "# Review and keep this file private because it contains bot credentials.",
    ""
  ].join("\n");

  return `${header}${serializeEnvironmentFile(entries)}`;
}

export function resolveSetupValues(
  existingEnv: NodeJS.ProcessEnv,
  inputValues: SetupInputValues,
  options: { readonly homeDir?: string } = {}
): SetupResolvedValues {
  const resolvedHomeDir = resolve(options.homeDir ?? homedir());
  const defaults = {
    nodeEnv: "production",
    defaultWorkspaceRoot: join(resolvedHomeDir, "codex-workspaces", "main"),
    appHome: join(resolvedHomeDir, ".local", "share", "codex-telegram-bridge"),
    codexHome: join(resolvedHomeDir, ".codex"),
    logLevel: "info"
  } as const;

  const allowedTelegramUserIds = (
    inputValues.allowedTelegramUserIds ??
    existingEnv.CODEX_TELEGRAM_BRIDGE_ALLOWED_TELEGRAM_USER_IDS ??
    ""
  ).trim();
  const ownerTelegramUserId = (
    inputValues.ownerTelegramUserId ??
    existingEnv.CODEX_TELEGRAM_BRIDGE_OWNER_TELEGRAM_USER_ID ??
    deriveOwnerFromAllowlist(allowedTelegramUserIds) ??
    ""
  ).trim();

  return {
    nodeEnv:
      (
        inputValues.nodeEnv ??
        existingEnv.NODE_ENV ??
        defaults.nodeEnv
      ).trim() || defaults.nodeEnv,
    telegramBotToken: (
      inputValues.telegramBotToken ??
      existingEnv.CODEX_TELEGRAM_BRIDGE_TELEGRAM_BOT_TOKEN ??
      ""
    ).trim(),
    verificationPasswordHash: resolveVerificationPasswordHash(
      existingEnv,
      inputValues
    ),
    allowedTelegramUserIds,
    defaultWorkspaceRoot: resolve(
      (
        inputValues.defaultWorkspaceRoot ??
        existingEnv.CODEX_TELEGRAM_BRIDGE_DEFAULT_WORKSPACE_ROOT ??
        defaults.defaultWorkspaceRoot
      ).trim() || defaults.defaultWorkspaceRoot
    ),
    appHome: resolve(
      (
        inputValues.appHome ??
        existingEnv.CODEX_TELEGRAM_BRIDGE_APP_HOME ??
        defaults.appHome
      ).trim() || defaults.appHome
    ),
    codexHome: resolve(
      (
        inputValues.codexHome ??
        existingEnv.CODEX_TELEGRAM_BRIDGE_CODEX_HOME ??
        existingEnv.CODEX_HOME ??
        defaults.codexHome
      ).trim() || defaults.codexHome
    ),
    logLevel: normalizeLogLevel(
      (
        inputValues.logLevel ??
        existingEnv.CODEX_TELEGRAM_BRIDGE_LOG_LEVEL ??
        defaults.logLevel
      ).trim() || defaults.logLevel
    ),
    ownerTelegramUserId: ownerTelegramUserId === "" ? null : ownerTelegramUserId
  };
}

export function buildEnvironmentEntries(
  existingEnv: NodeJS.ProcessEnv,
  values: SetupResolvedValues
): readonly [string, string][] {
  const knownEntries: [string, string][] = [
    ["NODE_ENV", values.nodeEnv],
    ["CODEX_TELEGRAM_BRIDGE_TELEGRAM_BOT_TOKEN", values.telegramBotToken],
    ...(values.verificationPasswordHash
      ? [
          [
            "CODEX_TELEGRAM_BRIDGE_VERIFICATION_PASSWORD_HASH",
            values.verificationPasswordHash
          ] as [string, string]
        ]
      : []),
    [
      "CODEX_TELEGRAM_BRIDGE_ALLOWED_TELEGRAM_USER_IDS",
      values.allowedTelegramUserIds
    ],
    [
      "CODEX_TELEGRAM_BRIDGE_DEFAULT_WORKSPACE_ROOT",
      values.defaultWorkspaceRoot
    ],
    ["CODEX_TELEGRAM_BRIDGE_APP_HOME", values.appHome],
    ["CODEX_TELEGRAM_BRIDGE_CODEX_HOME", values.codexHome],
    ["CODEX_TELEGRAM_BRIDGE_LOG_LEVEL", values.logLevel]
  ];

  if (values.ownerTelegramUserId) {
    knownEntries.push([
      "CODEX_TELEGRAM_BRIDGE_OWNER_TELEGRAM_USER_ID",
      values.ownerTelegramUserId
    ]);
  }

  const knownKeys = new Set(knownEntries.map(([key]) => key));
  const passthroughEntries = Object.entries(existingEnv)
    .filter(([key, value]) => value !== undefined && !knownKeys.has(key))
    .sort(([left], [right]) => left.localeCompare(right)) as [string, string][];

  return [...knownEntries, ...passthroughEntries];
}

export function normalizeOptionalValue(value: string): string | null {
  const trimmed = value.trim();
  return trimmed === "" ? null : trimmed;
}

export function normalizeLogLevel(value: string): AppLogLevel {
  const normalizedValue = value.trim().toLowerCase();
  if (
    normalizedValue === "debug" ||
    normalizedValue === "info" ||
    normalizedValue === "warn" ||
    normalizedValue === "error"
  ) {
    return normalizedValue;
  }

  return "info";
}

export function deriveOwnerFromAllowlist(value: string): string | null {
  const ids = value
    .split(",")
    .map((entry) => entry.trim())
    .filter(Boolean);

  return ids.length === 1 ? (ids[0] ?? null) : null;
}

function resolveVerificationPasswordHash(
  existingEnv: NodeJS.ProcessEnv,
  inputValues: SetupInputValues
): string | null {
  if (inputValues.verificationPasswordHash !== undefined) {
    return normalizeOptionalValue(inputValues.verificationPasswordHash);
  }

  if (inputValues.verificationPassword !== undefined) {
    const normalizedPassword = normalizeVerificationPassword(
      inputValues.verificationPassword
    );
    return normalizedPassword === ""
      ? null
      : hashVerificationPassword(normalizedPassword);
  }

  return normalizeOptionalValue(
    existingEnv.CODEX_TELEGRAM_BRIDGE_VERIFICATION_PASSWORD_HASH ?? ""
  );
}
