import assert from "node:assert/strict";
import { resolve } from "node:path";
import test from "node:test";
import { verifyVerificationPassword } from "../../src/security/verification-password.js";
import {
  buildEnvironmentEntries,
  parseSetupCommandArgs,
  renderEnvironmentFile,
  resolveSetupValues
} from "../../src/cli/setup.js";

test("resolveSetupValues fills user friendly defaults", () => {
  const values = resolveSetupValues({}, {}, { homeDir: "/home/alice" });

  assert.equal(values.nodeEnv, "production");
  assert.equal(
    values.defaultWorkspaceRoot,
    resolve("/home/alice/codex-workspaces/main")
  );
  assert.equal(
    values.appHome,
    resolve("/home/alice/.local/share/codex-telegram-bridge")
  );
  assert.equal(values.codexHome, resolve("/home/alice/.codex"));
  assert.equal(values.logLevel, "info");
  assert.equal(values.verificationPasswordHash, null);
  assert.equal(values.ownerTelegramUserId, null);
});

test("resolveSetupValues derives the owner from a single allowlisted user", () => {
  const values = resolveSetupValues(
    {},
    {
      allowedTelegramUserIds: "123456789"
    },
    { homeDir: "/home/alice" }
  );

  assert.equal(values.ownerTelegramUserId, "123456789");
});

test("resolveSetupValues hashes the verification password instead of storing plaintext", () => {
  const values = resolveSetupValues(
    {},
    {
      verificationPassword: "bridge-secret"
    },
    { homeDir: "/home/alice" }
  );

  assert.ok(values.verificationPasswordHash);
  assert.notEqual(values.verificationPasswordHash, "bridge-secret");
  assert.equal(
    verifyVerificationPassword(
      "bridge-secret",
      values.verificationPasswordHash ?? ""
    ),
    true
  );
});

test("buildEnvironmentEntries preserves unknown keys from an existing env file", () => {
  const entries = buildEnvironmentEntries(
    {
      CODEX_TELEGRAM_BRIDGE_CODEX_EXECUTABLE: "/usr/local/bin/codex"
    },
    resolveSetupValues(
      {},
      {
        telegramBotToken: "123456:token",
        verificationPassword: "bridge-secret",
        allowedTelegramUserIds: "123456789",
        defaultWorkspaceRoot: "/srv/workspaces/main",
        appHome: "/srv/app-home",
        codexHome: "/srv/.codex",
        logLevel: "warn"
      },
      { homeDir: "/home/alice" }
    )
  );

  assert.ok(
    entries.some(([key, value]) => {
      return (
        key === "CODEX_TELEGRAM_BRIDGE_CODEX_EXECUTABLE" &&
        value === "/usr/local/bin/codex"
      );
    })
  );
  assert.ok(
    entries.some(
      ([key]) => key === "CODEX_TELEGRAM_BRIDGE_VERIFICATION_PASSWORD_HASH"
    )
  );
});

test("parseSetupCommandArgs supports non-interactive configuration", () => {
  const parsed = parseSetupCommandArgs(
    [
      "--env-file",
      "/tmp/bridge.env",
      "--non-interactive",
      "--bot-token",
      "123456:token",
      "--allowed-user-id",
      "123456789",
      "--workspace-root",
      "/srv/workspaces/main"
    ],
    { homeDir: "/home/alice" }
  );

  assert.equal(parsed.envFilePath, resolve("/tmp/bridge.env"));
  assert.equal(parsed.interactive, false);
  assert.equal(parsed.values.telegramBotToken, "123456:token");
  assert.equal(parsed.values.allowedTelegramUserIds, "123456789");
  assert.equal(parsed.values.defaultWorkspaceRoot, "/srv/workspaces/main");
});

test("renderEnvironmentFile writes a readable setup header", () => {
  const rendered = renderEnvironmentFile([
    ["NODE_ENV", "production"],
    ["CODEX_TELEGRAM_BRIDGE_TELEGRAM_BOT_TOKEN", "123456:token"]
  ]);

  assert.match(rendered, /Generated by `codex-telegram-bridge setup`/);
  assert.match(
    rendered,
    /CODEX_TELEGRAM_BRIDGE_TELEGRAM_BOT_TOKEN=123456:token/
  );
});
